name: aoc2018
version: 0.1.0.0
github: ''
license: BSD3
author: 'Ben Hart'
maintainer: ''
copyright: ''

extra-source-files:
  - README.md
  - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: ''

dependencies:
  - base >= 4.7 && < 5

library:
  source-dirs: .
  dependencies:
    - array
    - containers
    - megaparsec
    - monad-loops
    - mtl
    - parallel
    - split
    - time
    - text

executables:
  aoc2018-exe:
    main: Main.hs
    source-dirs: .
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -pgmL markdown-unlit
    dependencies:
      - aoc2018
      - markdown-unlit

data-files:
  - day*.txt

tests:
  aoc2018-test:
    main: Main.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - aoc2018
      - hspec

benchmarks:
  aoc2018-bench:
    main: Main.hs
    source-dirs: bench
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - aoc2018
      - criterion
